import {
  W_OUSHOU,
  W_KINSHOU_L,
  W_KINSHOU_R,
  B_GYOKUSHOU,
  B_KINSHOU_L,
  B_KINSHOU_R
} from './piecesHigh';
import {
  W_RYUUOO,
  W_RYUUMA,
  W_NARIKYOU_L,
  W_NARIKYOU_R,
  W_NARIKEI_L,
  W_NARIKEI_R,
  W_NARIGIN_L,
  W_NARIGIN_R,
  W_TOKIN_1,
  W_TOKIN_2,
  W_TOKIN_3,
  W_TOKIN_4,
  W_TOKIN_5,
  W_TOKIN_6,
  W_TOKIN_7,
  W_TOKIN_8,
  W_TOKIN_9,
  B_RYUUOO,
  B_RYUUMA,
  B_NARIKYOU_L,
  B_NARIKYOU_R,
  B_NARIKEI_L,
  B_NARIKEI_R,
  B_NARIGIN_L,
  B_NARIGIN_R,
  B_TOKIN_1,
  B_TOKIN_2,
  B_TOKIN_3,
  B_TOKIN_4,
  B_TOKIN_5,
  B_TOKIN_6,
  B_TOKIN_7,
  B_TOKIN_8,
  B_TOKIN_9
} from './piecesPromoted';
import {
  W_HISHA,
  W_KAKUGYOU,
  W_KYOUSHA_L,
  W_KYOUSHA_R,
  W_KEIMA_L,
  W_KEIMA_R,
  W_GINSHOU_L,
  W_GINSHOU_R,
  W_FUHYOU_1,
  W_FUHYOU_2,
  W_FUHYOU_3,
  W_FUHYOU_4,
  W_FUHYOU_5,
  W_FUHYOU_6,
  W_FUHYOU_7,
  W_FUHYOU_8,
  W_FUHYOU_9,
  B_HISHA,
  B_KAKUGYOU,
  B_KYOUSHA_L,
  B_KYOUSHA_R,
  B_KEIMA_L,
  B_KEIMA_R,
  B_GINSHOU_L,
  B_GINSHOU_R,
  B_FUHYOU_1,
  B_FUHYOU_2,
  B_FUHYOU_3,
  B_FUHYOU_4,
  B_FUHYOU_5,
  B_FUHYOU_6,
  B_FUHYOU_7,
  B_FUHYOU_8,
  B_FUHYOU_9
} from './piecesRegular';

export const ALL_PIECES = {
  white: [
    W_OUSHOU,
    W_KINSHOU_L,
    W_KINSHOU_R,
    W_RYUUOO,
    W_RYUUMA,
    W_NARIKYOU_L,
    W_NARIKYOU_R,
    W_NARIKEI_L,
    W_NARIKEI_R,
    W_NARIGIN_L,
    W_NARIGIN_R,
    W_TOKIN_1,
    W_TOKIN_2,
    W_TOKIN_3,
    W_TOKIN_4,
    W_TOKIN_5,
    W_TOKIN_6,
    W_TOKIN_7,
    W_TOKIN_8,
    W_TOKIN_9,
    W_HISHA,
    W_KAKUGYOU,
    W_KYOUSHA_L,
    W_KYOUSHA_R,
    W_KEIMA_L,
    W_KEIMA_R,
    W_GINSHOU_L,
    W_GINSHOU_R,
    W_FUHYOU_1,
    W_FUHYOU_2,
    W_FUHYOU_3,
    W_FUHYOU_4,
    W_FUHYOU_5,
    W_FUHYOU_6,
    W_FUHYOU_7,
    W_FUHYOU_8,
    W_FUHYOU_9
  ],
  black: [
    B_GYOKUSHOU,
    B_KINSHOU_L,
    B_KINSHOU_R,
    B_RYUUOO,
    B_RYUUMA,
    B_NARIKYOU_L,
    B_NARIKYOU_R,
    B_NARIKEI_L,
    B_NARIKEI_R,
    B_NARIGIN_L,
    B_NARIGIN_R,
    B_TOKIN_1,
    B_TOKIN_2,
    B_TOKIN_3,
    B_TOKIN_4,
    B_TOKIN_5,
    B_TOKIN_6,
    B_TOKIN_7,
    B_TOKIN_8,
    B_TOKIN_9,
    B_HISHA,
    B_KAKUGYOU,
    B_KYOUSHA_L,
    B_KYOUSHA_R,
    B_KEIMA_L,
    B_KEIMA_R,
    B_GINSHOU_L,
    B_GINSHOU_R,
    B_FUHYOU_1,
    B_FUHYOU_2,
    B_FUHYOU_3,
    B_FUHYOU_4,
    B_FUHYOU_5,
    B_FUHYOU_6,
    B_FUHYOU_7,
    B_FUHYOU_8,
    B_FUHYOU_9
  ]
};

export const DEMOTIONS = {
  white_ryūō: W_HISHA,
  white_ryūma: W_KAKUGYOU,
  white_narikyō_L: W_KYOUSHA_L,
  white_narikyō_R: W_KYOUSHA_R,
  white_narikei_L: W_KEIMA_L,
  white_narikei_R: W_KEIMA_R,
  white_narigin_L: W_GINSHOU_L,
  white_narigin_R: W_GINSHOU_R,
  white_tokin_1: W_FUHYOU_1,
  white_tokin_2: W_FUHYOU_2,
  white_tokin_3: W_FUHYOU_3,
  white_tokin_4: W_FUHYOU_4,
  white_tokin_5: W_FUHYOU_5,
  white_tokin_6: W_FUHYOU_6,
  white_tokin_7: W_FUHYOU_7,
  white_tokin_8: W_FUHYOU_8,
  white_tokin_9: W_FUHYOU_9,
  black_ryūō: B_HISHA,
  black_ryūma: B_KAKUGYOU,
  black_narikyō_L: B_KYOUSHA_L,
  black_narikyō_R: B_KYOUSHA_R,
  black_narikei_L: B_KEIMA_L,
  black_narikei_R: B_KEIMA_R,
  black_narigin_L: B_GINSHOU_L,
  black_narigin_R: B_GINSHOU_R,
  black_tokin_1: B_FUHYOU_1,
  black_tokin_2: B_FUHYOU_2,
  black_tokin_3: B_FUHYOU_3,
  black_tokin_4: B_FUHYOU_4,
  black_tokin_5: B_FUHYOU_5,
  black_tokin_6: B_FUHYOU_6,
  black_tokin_7: B_FUHYOU_7,
  black_tokin_8: B_FUHYOU_8,
  black_tokin_9: B_FUHYOU_9
};

export const PROMOTIONS = {
  white_hisha: W_RYUUOO,
  white_kakugyō: W_RYUUMA,
  white_kyōsha_L: W_NARIKYOU_L,
  white_kyōsha_R: W_NARIKYOU_R,
  white_keima_L: W_NARIKEI_L,
  white_keima_R: W_NARIKEI_R,
  white_ginshō_L: W_NARIGIN_L,
  white_ginshō_R: W_NARIGIN_R,
  white_fuhyō_1: W_TOKIN_1,
  white_fuhyō_2: W_TOKIN_2,
  white_fuhyō_3: W_TOKIN_3,
  white_fuhyō_4: W_TOKIN_4,
  white_fuhyō_5: W_TOKIN_5,
  white_fuhyō_6: W_TOKIN_6,
  white_fuhyō_7: W_TOKIN_7,
  white_fuhyō_8: W_TOKIN_8,
  white_fuhyō_9: W_TOKIN_9,
  black_hisha: B_RYUUOO,
  black_kakugyō: B_RYUUMA,
  black_kyōsha_L: B_NARIKYOU_L,
  black_kyōsha_R: B_NARIKYOU_R,
  black_keima_L: B_NARIKEI_L,
  black_keima_R: B_NARIKEI_R,
  black_ginshō_L: B_NARIGIN_L,
  black_ginshō_R: B_NARIGIN_R,
  black_fuhyō_1: B_TOKIN_1,
  black_fuhyō_2: B_TOKIN_2,
  black_fuhyō_3: B_TOKIN_3,
  black_fuhyō_4: B_TOKIN_4,
  black_fuhyō_5: B_TOKIN_5,
  black_fuhyō_6: B_TOKIN_6,
  black_fuhyō_7: B_TOKIN_7,
  black_fuhyō_8: B_TOKIN_8,
  black_fuhyō_9: B_TOKIN_9
};
